name: Build Preprod Pages

on:
  push:
    branches:
      - preprod-v2  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.94.2'
          extended: true

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/preprod-v2' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: pages-preprod
          publish_dir: ./dist
          destination_dir: dist
